files = {
        "BKC": "data\BandraKurlaComplexMumbaiIITM.csv",
        "BandraMPCB": "data\BandraMumbaiMPCB.csv",
        "BoriValiEastIITM": "data\BorivaliEastMumbaiIITM.csv",
        "BoriValiEastMPCB": "data\BorivaliEastMumbaiMPCB.csv",
        "AndheriEast": "data\ChakalaAndheriEastMumbaiIITM.csv",
        "VileParleWestMumbai": "data\VileParleWestMumbaiMPCB.csv",
        "VasaiWestMumbai": "data\VasaiWestMumbaiMPCB.csv",
        "SionMumbai": "data\SionMumbaiMPCB.csv",
        "SiddharthNagarWorli": "data\SiddharthNagarWorliMumbaiIITM.csv",
        "PowaiMumbai": "data\PowaiMumbaiMPCB.csv",
        "NavyNagarColaba": "data/NavyNagarColabaMumbaiIITM.csv",
        "MulundWestMumbai": "data\MulundWestMumbaiMPCB.csv",
        "MazgaonMumbai": "data\MazgaonMumbaiIITM.csv",
        "MaladWestMumbai": "data\MaladWestMumbaiIITM.csv",
        "KurlaMumbai": "data\KurlaMumbaiMPCB.csv",
        "KhindipadaBhandupWestMumbai": "data\KhindipadaBhandupWestMumbaiIITM.csv",
        "KandivaliEastMumbai": "data\KandivaliEastMumbaiMPCB.csv",
        "DeonarMumbai": "data\DeonarMumbaiIITM.csv",
        "ColabaMumbai": "data\ColabaMumbaiMPCB.csv",
        "ChhatrapatiShivajiIntlAirport": "data\ChhatrapatiShivajiIntlAirportT2MumbaiMPCB.csv",
        "ChakalaAndheri": "data\ChakalaAndheriEastMumbaiIITM.csv",
        "Worli": "data\WorliMumbaiMPCB.csv"
    }
